### PR TITLE
Use refcounted classes for Shader / ShaderProgram

### PR DESCRIPTION
**Pull request by ArthurSonzogni**
@TheMaverickProgrammer prefers a reference instead of a pointer:

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
@TheMaverickProgrammer WDYT?

I am providing an overload taking both a pointer or a reference. You might be against it. On the other side, I don't want to do pointer->reference or reference->pointer conversion in the code. So I am divided.

**Comment by TheMaverickProgrammer** [comment]
why do you want to pass a shader program as a pointer exactly?

**Comment by ArthurSonzogni** [comment]
Maybe we could keep the existing class name, but define it as a shared_ptr over the implementation class.
Something like:
```
class ShaderImpl;
using Shader = std::shared_ptr<ShaderImpl>
```

Then Shader / ShaderProgram will have move semantics for free, and will be refcounted.

-----

Alternatively, I can make it refcounted internally:
I already did this for VertexArray:
https://github.com/ArthurSonzogni/smk/blob/master/include/smk/VertexArray.hpp#L51

Not sure what is preferable.

**Comment by TheMaverickProgrammer** [comment]
I would definitely avoid alias with `using`. Someone might accidentally `Shader* my_shader` and not understand.

I do like your idea of internally reference counting for shaders as well. Then you can just pass the shader object as a copy operation

**Pull request merged**
